gather_sriov - fix when multiple subs for same operator exists across all namespaces
Signed-off-by: Vladislav Walek <22072258+vwalek@users.noreply.github.com>

diff --git a/collection-scripts/gather_sriov b/collection-scripts/gather_sriov
--- a/collection-scripts/gather_sriov
+++ b/collection-scripts/gather_sriov
@@ -1,14 +1,19 @@
 #!/bin/bash
 
 BASE_COLLECTION_PATH="must-gather"
-SRIOV_NS="$(oc get subs -A -o template --template '{{range .items}}{{if eq .spec.name "sriov-network-operator"}}{{.metadata.namespace}}{{end}}{{end}}')"
-SRIOV_LOG_PATH="${BASE_COLLECTION_PATH}/namespaces/${SRIOV_NS}"
-
+SRIOV_NS="$(oc get subs -A -o template --template '{{range .items}}{{if eq .spec.name "sriov-network-operator"}}{{.metadata.namespace}}{{"\n"}}{{end}}{{end}}' | sort | uniq)"
 
 if [ -z "${SRIOV_NS}" ]; then
     echo "INFO: SR-IOV not detected. Skipping."
     exit 0
 fi
+
+if [[ "$(echo "${SRIOV_NS}" | wc -l)">1 ]]; then
+    echo "ERROR: SRIOV installed in more than 1 namespace. Exiting."
+    exit 1
+fi
+
+SRIOV_LOG_PATH="${BASE_COLLECTION_PATH}/namespaces/${SRIOV_NS}"
 
 # resource list
 resources=()
